[Project]
name = "MQGA"
version = "0.1.0"
authors = [
    "Liggest",
    "duolanda",
    "liuyu.fang",
]
description = "Mostly a QQ Group Assistant"
address = "https://github.com/liggest/MQGA"
license = "MIT"
license_file = "LICENSE"
copyright = "Copyright (c) 2021 Liggest"

[Config]
AppID = "123"
Token = ""
Secret = "123"
